"""
Pydantic models for API request/response contracts.

Typed contracts prevent silent errors and automatically document the
endpoint in the Swagger UI exposed at /docs.
"""
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Body expected by POST /chat."""

    api_key: str = Field(..., description="API authentication token")
    message: str = Field(..., min_length=1, description="Message sent by the end user")
    user_id: str = Field(
        ...,
        min_length=1,
        description="Unique identifier for the user (e.g. phone number)",
    )


class ChatResponse(BaseModel):
    """Response body of POST /chat."""

    reply: str = Field(..., description="Reply generated by the assistant")


class HealthResponse(BaseModel):
    """Response body of GET /health."""

    status: str = Field(default="ok")
    active_sessions: int = Field(..., description="Number of in-memory conversations")
    catalog_items: int = Field(..., description="Number of items loaded from the catalog")
    handoff_strategy: str = Field(..., description="Configured handoff strategy")
